version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: wzuser
      POSTGRES_PASSWORD: wzuser
      POSTGRES_DB: webzaim
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ttwebzaim-postgres-1:5432/webzaim
      SPRING_DATASOURCE_USERNAME: wzuser
      SPRING_DATASOURCE_PASSWORD: wzuser
    ports:
      - "8080:8080"

volumes:
  postgres_data:
